server:
  port: 9000
  servlet:
    context-path: /user

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro-user?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka