server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false   # eureka의 registry에 등록할지 여부 (default = true)
    fetch-registry: false         # registy에 있는 정보를 가져올지 여부 (default = true)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/